### ISSUE TITLE
MACOS not working

### ISSUE THREAD

**Issue by WMXPY** [WMXPY/Ghoti-CLI#6]
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/react-normal'
    at Object.fs.readdirSync (fs.js:904:18)
    at copyInitReacursion (/Users/Cheng/Desktop/git/Ghoti-CLI/dist/func/init.js:70:16)
    at copyInit (/Users/Cheng/Desktop/git/Ghoti-CLI/dist/func/init.js:96:12)
    at /Users/Cheng/Desktop/git/Ghoti-CLI/dist/func/init.js:116:7
    at /Users/Cheng/Desktop/git/Ghoti-CLI/dist/func/parser.js:125:22
    at /Users/Cheng/Desktop/git/Ghoti-CLI/dist/func/parser.js:94:7
    at Interface._onLine (readline.js:280:5)
    at Interface._normalWrite (readline.js:424:12)
    at ReadStream.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)

**Comment by WMXPY** [comment]
Fixed
